const quizData = [
    {
      //question: 'What is the capital of France?',
      question: "<img src='banjo/headcrack.png' style='height: 200px' '></img>",
        //"<h2 style = 'text-align: center'>Select the defect <br> दोष का चयन करें </h2> <img src='banjo/headcrack.png' style='height: 200px' '></img>",
      value: "q1",
      options: [
        "Ok Sample",
        "Head Dent Mark",
        "Head Pit Mark",
        "Head Crack",
      ],
      answer: "Head Crack",
    },
    {
      //question: 'What is the largest planet in our solar system?',
      question: "<img src='banjo/shankpitmark.png' style='height: 200px' '> </img>",
        //"<h2 style = 'text-align: center'>Select the defect <br> दोष का चयन करें </h2> <img src='banjo/shankpitmark.png' style='height: 200px' '> </img>",
      value: "q2",
      options: [
        "Ok Sample",
        "Shank Pit Mark",
        "Poor Finish",
        "Shank Line Mark",
      ],
      answer: "Shank Pit Mark",
    },
    {
      //question: 'Which country won the FIFA World Cup in 2018?',
      question: "<img src='banjo/headdentmark.png' style='height: 200px' '> </img>",
        //"<h2 style = 'text-align: center'>Select the defect <br> दोष का चयन करें </h2> <img src='banjo/headdentmark.png' style='height: 200px' '> </img>",
      value: "q3",
      options: [
        "Ok Sample",
        "Head Damage",
        "Head Pit Mark",
        "Head Dent Mark",
      ],
      answer: "Head Dent Mark",
    },
    {
      //question: 'What is the tallest mountain in the world?',
      question: "<img src='banjo/linemark.png' style='height: 200px' '> </img>",
        //"<h2 style = 'text-align: center'>Select the defect <br> दोष का चयन करें </h2> <img src='banjo/linemark.png' style='height: 200px' '> </img>",
      value: "q4",
      options: ["Shank Damage", "Shank Dent Mark", "Shank Line Mark", "Ok Sample"],
      answer: "Shank Line Mark",
    },
    {
      //question: 'Which is the largest ocean on Earth?',
      question: "<img src='banjo/pitmark.png' style='height: 200px' '> </img>",
        //"<h2 style = 'text-align: center'>Select the defect <br> दोष का चयन करें </h2> <img src='banjo/pitmark.png' style='height: 200px' '> </img>",
      value: "q5",
      options: ["Head Chamber Uneven", "Ok Sample", "Head Damage", "Head Pit Mark"],
      answer: "Head Pit Mark",
    },
    {
      //question: 'What is the chemical symbol for gold?',
      question: "<img src='banjo/shankdamage.png' style='height: 200px' '> </img>",
        //"<h2 style = 'text-align: center'>Select the defect  <br> दोष का चयन करें </h2> <img src='banjo/shankdamage.png' style='height: 200px' '> </img>",
      value: "q6",
      options: ["Poor Finish", "Shank Dent Mark", "Ok Sample", "Shank Damage"],
      answer: "Shank Damage",
    },
    {
      //question: 'Who painted the Mona Lisa?',
      question: "<img src='banjo/shankdamage1.png' style='height: 200px' '> </img>",
        //"<h2 style = 'text-align: center'>Select the defect <br> दोष का चयन करें </h2> <img src='banjo/shankdamage1.jpg' style='height: 200px' '> </img>",
      value: "q7",
      options: [
        "Poor Finish", "Shank Dent Mark", "Ok Sample", "Shank Damage",
      ],
      answer: "Shank Damage",
    },
    {
      //question: 'Which planet is known as the Red Planet?',
      question: "<img src='banjo/acrossflatunderfill.png' style='height: 200px' '> </img>",
        //"<h2 style = 'text-align: center'>Select the defect <br> दोष का चयन करें </h2> <img src='banjo/acrossflatunderfill.png' style='height: 200px' '> </img>",
      value: "q8",
      options: [
        "Across Flat Under Fill",
        "Head Dent Mark",
        "Poor Finish",
        "Ok Sample",
      ],
      answer: "Across Flat Under Fill",
    },
    {
      //question: 'What is the largest species of shark?',
      question: "<img src='banjo/acrossflatunderfill1.png' style='height: 200px' '> </img>",
        //"<h2 style = 'text-align: center'>Select the defect <br> दोष का चयन करें </h2> <img src='banjo/acrossflatunderfill1.png' style='height: 200px' '> </img>",
      value: "q9",
      options: [
        "Ok Sample",
        "Head Crack",
        "Poor Finish",
        "Across Flat Under Fill",
      ],
      answer: "Across Flat Under Fill",
    },
    {
      //question: 'Which animal is known as the King of the Jungle?',
      question: "<img src='banjo/headdentmark2.png' style='height: 200px' '> </img>",
      //`<h2 style = 'text-align: center'>Select the defect <br> दोष का चयन करें </h2> <img src='banjo/headdentmark2.png' style='height: 200px' '> </img>`,
      value: "q10",
      options: [
        "Ok Sample",
        "Head Pit Mark",
        "Head Damage",
        "Head Dent Mark",
      ],
      answer: "Head Dent Mark",
    } ,
    {
      //question: 'What is the capital of France?',
      question: "<img src='banjo/oksample.png' style='height: 200px; padding-top:2px;' '></img>",
        //"<h2 style = 'text-align: center; font-size:25px;'>Select the defect   <br> दोष का चयन करें</h2> <img src='banjo/headcrack.png' style='height: 200px; padding-top:2px;' '></img>",
      value: "q11",
      options: [
        "Bearingface Underfill",
        "Ok Sample",
        "Head Pit Mark",
        "Head Crack",
      ],
      answer: "Ok Sample",
    },
    {
      //question: 'What is the largest planet in our solar system?',
      question: "<img src='banjo/oksample1.png' style='height: 200px; padding-top:2px;' '></img>",
        //"<h2 style = 'text-align: center; font-size:25px;'>Select the defect  <br> दोष का चयन करें </h2> <img src='banjo/poorfinish.png' style='height: 200px; padding-top:2px;' '> </img>",
      value: "q12",
      options: [
        "Ok Sample",
        "Shank Pit Mark",
        "Poor Finish",
        "Bearingface Underfill",
      ],
      answer: "Ok Sample",
    },
    {
      //question: 'Which country won the FIFA World Cup in 2018?',
      question: "<img src='banjo/oksample2.png' style='height: 200px; padding-top:2px;' '></img>",
        //"<h2 style = 'text-align: center; font-size:25px;'>Select the defect  <br> दोष का चयन करें </h2> <img src='banjo/headdentmark.png' style='height: 200px; padding-top:2px;' '> </img>",
      value: "q13",
      options: [
        "Ok Sample",
        "Head Damage",
        "Bearingface Underfill",
        "Thread Damage",
      ],
      answer: "Ok Sample",
    },
    {
      //question: 'What is the tallest mountain in the world?',
      question: "<img src='banjo/oksample3.png' style='height: 200px; padding-top:2px;' '></img>",
        //"<h2 style = 'text-align: center; font-size:25px;'>Select the defect  <br> दोष का चयन करें </h2> <img src='banjo/linemark.png' style='height: 200px; padding-top:2px;' '> </img>",
      value: "q14",
      options: ["Shank Damage", "Shank Dent Mark", "Ok Sample", "Head Dent Mark"],
      answer: "Ok Sample",
    },
    {
      //question: 'Which is the largest ocean on Earth?',
      question: "<img src='banjo/headcrack.png' style='height: 200px; padding-top:2px;' '></img>",
        //"<h2 style = 'text-align: center; font-size:25px;'>Select the defect  <br> दोष का चयन करें </h2> <img src='banjo/pitmark.png' style='height: 200px; padding-top:2px;' '> </img>",
      value: "q15",
      options: [
        "Head Chamber Uneven",
        "Head Burr",
        "Ok Sample",
        "Head Crack",
      ],
      answer: "Head Crack",
    } ,
    {
      //question: 'What is the capital of France?',
      question: "<img src='banjo/headdentmark1.png' style='height: 200px; padding-top:2px;' '></img>",
        //"<h2 style = 'text-align: center; font-size:25px;'>Select the defect   <br> दोष का चयन करें</h2> <img src='banjo/headcrack.png' style='height: 200px; padding-top:2px;' '></img>",
      value: "q16",
      options: [
        "Head Dent Mark",
        "Ok Sample",
        "Head Pit Mark",
        "Head Crack",
      ],
      answer: "Head Dent Mark",
    },
    {
      //question: 'What is the largest planet in our solar system?',
      question: "<img src='banjo/shankpitmark.png' style='height: 200px; padding-top:2px;' '> </img>",
        //"<h2 style = 'text-align: center; font-size:25px;'>Select the defect  <br> दोष का चयन करें </h2> <img src='banjo/poorfinish.png' style='height: 200px; padding-top:2px;' '> </img>",
      value: "q17",
      options: [
        "Ok Sample",
        "Shank Pit Mark",
        "Poor Finish",
        "Bearingface Underfill",
      ],
      answer: "Shank Pit Mark",
    },
    {
      //question: 'Which country won the FIFA World Cup in 2018?',
      question: "<img src='banjo/headdentmark.png' style='height: 200px; padding-top:2px;' '> </img>",
        //"<h2 style = 'text-align: center; font-size:25px;'>Select the defect  <br> दोष का चयन करें </h2> <img src='banjo/headdentmark.png' style='height: 200px; padding-top:2px;' '> </img>",
      value: "q18",
      options: [
        "Ok Sample",
        "Head Damage",
        "Bearingface Underfill",
        "Head Dent Mark",
      ],
      answer: "Head Dent Mark",
    },
    {
      //question: 'What is the tallest mountain in the world?',
      question: "<img src='banjo/linemark.png' style='height: 200px; padding-top:2px;' '> </img>",
        //"<h2 style = 'text-align: center; font-size:25px;'>Select the defect  <br> दोष का चयन करें </h2> <img src='banjo/linemark.png' style='height: 200px; padding-top:2px;' '> </img>",
      value: "q19",
      options: ["Shank Damage", "Ok Sample", "Shank Line Mark", "Head Dent Mark"],
      answer: "Shank Line Mark",
    },
    {
      //question: 'Which is the largest ocean on Earth?',
      question: "<img src='banjo/pitmark.png' style='height: 200px; padding-top:2px;' '> </img>",
        //"<h2 style = 'text-align: center; font-size:25px;'>Select the defect  <br> दोष का चयन करें </h2> <img src='banjo/pitmark.png' style='height: 200px; padding-top:2px;' '> </img>",
      value: "q20",
      options: [
        "Head Chamber Uneven",
        "Head Burr",
        "Ok Sample",
        "Head Pit Mark",
      ],
      answer: "Head Pit Mark",
    } 
    /*,
      {
        //question: 'What is the chemical symbol for gold?',
        question:
          "<h2 style = 'text-align: center'>Select the defect 6  <br> दिए गए नमूने 6 के लिए दोष का चयन करें </h2> <img src='banjo/headburr.png' style='height: 200px; padding-top:2px;' '> </img>",
        value: "q6",
        options: ["Head Burr", "Shank Damage", "Head Crack", "Head Dent Mark"],
        answer: "Head Burr",
      } ,
      {
        //question: 'Who painted the Mona Lisa?',
        question:
          "<h2 style = 'text-align: center'>Select the defect 7 <br> दिए गए नमूने 7 के लिए दोष का चयन करें </h2> <img src='groupedImages/headchamberuneven.jpg' style='height: 200px' '> </img>",
        value: "q7",
        options: [
          "Head Burr",
          "Head Chamber Damage",
          "Head Chamber Uneven",
          "Head Damage",
        ],
        answer: "Head Chamber Uneven",
      },
      {
        //question: 'Which planet is known as the Red Planet?',
        question:
          "<h2 style = 'text-align: center'>Select the defect 8 <br> दिए गए नमूने 8 के लिए दोष का चयन करें </h2> <img src='groupedImages/impropermeccoating.jpg' style='height: 200px' '> </img>",
        value: "q8",
        options: [
          "Improper MEC Coating",
          "Improper MEC Tip Cleaning",
          "Poor Finish",
          "Improper Finish",
        ],
        answer: "Improper MEC Coating",
      },
      {
        //question: 'What is the largest species of shark?',
        question:
          "<h2 style = 'text-align: center'>Select the defect 9 <br> दिए गए नमूने 9 के लिए दोष का चयन करें </h2> <img src='groupedImages/impropermectipcleaning.jpg' style='height: 200px' '> </img>",
        value: "q9",
        options: [
          "Improper MEC Coating",
          "Poor Finish",
          "Poor MEC Coating",
          "Improper MEC Tip Cleaning",
        ],
        answer: "Improper MEC Tip Cleaning",
      },
      {
        //question: 'Which animal is known as the King of the Jungle?',
        question: `<h2 style = 'text-align: center'>Select the defect 10 <br> दिए गए नमूने 10 के लिए दोष का चयन करें </h2> <img src='groupedImages/Materialdeposit.jpg' style='height: 200px' '> </img>`,
        value: "q10",
        options: [
          "Head Damage",
          "Material Deposit",
          "Uneven Paint",
          "Poor Yellow Paint Mark",
        ],
        answer: "Material Deposit",
      },
      
          {
            //question: 'Which animal is known as the King of the Jungle?',
            question: "<img src='groupedImages/pointingdamage.jpg' style='height: 200px' '> </img>",
            options: ['Bearing Face Convex', 'Bearing Face Underfill', 'Pointing Damage', 'White Patches'],
            answer: 'Pointing Damage',
          },
          {
            //question: 'Which animal is known as the King of the Jungle?',
            question: "<img src='groupedImages/poorfinish.jpg' style='height: 200px' '> </img>",
            options: ['Poor Finish', 'Poor MEC Coating', 'Thread Damage', 'Shank Damage'],
            answer: 'Poor Finish',
          },
          {
            //question: 'Which animal is known as the King of the Jungle?',
            question: "<img src='groupedImages/poorfinish1.jpg' style='height: 200px' '> </img>",
            options: ['Shank Damage', 'Poor Finish', 'Thread Damage', 'Poor MEC Coating'],
            answer: 'Poor Finish',
          },
          {
            //question: 'Which animal is known as the King of the Jungle?',
            question: "<img src='groupedImages/poormeccoating.jpg' style='height: 200px' '> </img>",
            options: ['Poor Finish', 'Dent Mark', 'Improper MEC Coating', 'Poor MEC Coating'],
            answer: 'Poor MEC Coating',
          },
          
      
          */
  ];